PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX rdac: <http://rdaregistry.info/Elements/c/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>

select distinct   ?entity ?label
				FROM DEFAULT
				WHERE {
  		        ?entity rdf:type ?type.
    	          ?type rdfs:label ?label.
  		        ?type rdfs:subClassOf rdac:C10013.
    	          FILTER(LANG(?label) = "gden")
}


