#Part of relationships
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdae: <http://rdaregistry.info/Elements/e/object/>
prefix rdaw: <http://rdaregistry.info/Elements/w/object/>
prefix rdax: <http://rdaregistry.info/Elements/x/object/>

select distinct ?s ?p ?l ?o WHERE {
{?s ?p ?o.
        ?p rdfs:subPropertyOf* rdaw:P10019.
        ?p rdfs:label ?l.}
    UNION
    {?s ?p ?o.
        ?p rdfs:subPropertyOf* rdae:P20074.
        ?p rdfs:label ?l.}
}